# Generated by Django 4.2 on 2023-05-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sebe',
            fields=[
                ('tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imga', models.ImageField(upload_to=None, verbose_name='')),
                ('imgb', models.ImageField(upload_to=None, verbose_name='')),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Seba',
        ),
    ]
