# Generated by Django 4.2 on 2023-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sebe_delete_seba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebe',
            name='imga',
            field=models.ImageField(upload_to='media', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sebe',
            name='imgb',
            field=models.ImageField(upload_to='media', verbose_name=''),
        ),
    ]
