# Generated by Django 4.2 on 2023-05-16 05:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sebe_imga_alter_sebe_imgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebe',
            name='imga',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.filepath),
        ),
        migrations.AlterField(
            model_name='sebe',
            name='imgb',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.filepath),
        ),
    ]
