"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n^pe2ehl(ex)ocbp1+%!@@xssc4*0y#t!#d=%jj)ixhpqdikku'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['C:/Users/sebas/OneDrive/Escritorio/proyecto/myproject/users/users/web'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = { # for sql on xamp install "mysqlclient"
    'default': {
        'ENGINE': 'django.db.backends.mysql', #motor de la base de datos # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'proyectodjango', #hombre de la base de datos
        'USER': 'root', #usuario de la base de datos
        'PASSWORD': '', #contraseña de la base de datos
        'HOST': 'localhost', #host de la base de datos
        'PORT': '3306', #puerto de la base de datos
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'" #por los errores a warning
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA_ROOT =  ["C:/Users/sebas/OneDrive/Escritorio/proyecto/myproject/users/uploads"]
# MEDIA_URL = 'uploads'


MEDIA_URL = "/uploads/"
MEDIA_ROOT=os.path.join(BASE_DIR,"uploads/")


# TRANSBANK_WEBPAY_PLUS_COMMERCE_CODE = '597055555532'
# TRANSBANK_WEBPAY_PLUS_API_KEY_SECRET = '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
# TRANSBANK_WEBPAY_PLUS_ENVIRONMENT = 'INTEGRATION' # Cambiar a 'LIVE' para producción
# Obtener variable de entorno o asignar un valor predeterminado

# Configuración de PayPal
STRIPE_SECRET_KEY = "sk_test_51N8wZpK3vZAXhbV0YCtRASbSX8g9xNxFH52h6MOVBhaJBcD13RWvff7EXkxmiWv9hx4GIOxPwkJZQiA2QBaXRZr000oLTy8Ka3"
STRIPE_PUBLISHABLE_KEY = "pk_test_51N8wZpK3vZAXhbV08uDOG4j7Cw9X529Z7vlOgQiGfn2lVdltPjWKwiWJrWwfvDvPQt6eZSq7jNjMyTKRPIHXyk1R00m4eC6Oup"

BACKEND_DOMAIN = "http://127.0.0.1:8000"
PAYMENT_SUCCESS_URL = "http://127.0.0.1:8000/success/"
PAYMENT_CANCEL_URL = "http://127.0.0.1:8000/cancel/"